FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

ADD . /repo
WORKDIR /repo
RUN chmod +x ./Build.sh
RUN ./Build.sh

RUN mkdir -p /deps
RUN ldd /repo/mksh | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:20.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /repo/mksh /repo/mksh
ENV LD_LIBRARY_PATH=/deps
